//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public decimal ID { get; set; }
        public Nullable<decimal> TestID { get; set; }
        public Nullable<decimal> UserID { get; set; }
        public Nullable<decimal> QuesID { get; set; }
        public string Ans { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
